### ISSUE TITLE
YouTube Nocookie URL Not Accepted

### ISSUE THREAD

**Issue by sprankhub** [magento/magento2-page-builder#826]
### Preconditions (*)
1. Magento 2.4.3-p3

### Steps to reproduce (*)
1. Create CMS page.
2. Use page builder to add content.
3. Add video element. Enter https://www.youtube-nocookie.com/embed/019DMLEVkos as "Video URL".
4. Click "Save" button.

### Expected result (*)
1. Video is correctly inserted without any error.

### Actual result (*)
1. Error message "Please enter a valid video URL. Valid URLs have a video file extension (.mp4, .webm, .ogv) or links to videos on YouTube or Vimeo." is shown:

![image](https://user-images.githubusercontent.com/930199/185367430-a73ce089-2d18-4265-8351-39174b5166fb.png)

**Comment by sprankhub** [comment]
@magento I am working on this

**Comment by engcom-Bravo** [comment]
Hi @sprankhub,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Create CMS page.
- Use page builder to add content.
- Add video element. Enter https://www.youtube-nocookie.com/embed/019DMLEVkos as "Video URL".
- Click "Save" button.

<img width="1496" alt="Screenshot 2023-11-24 at 2 16 40 PM" src="https://github.com/magento/magento2-page-builder/assets/51680745/67d4b448-3b28-4345-8271-e065d47e165d">



We are getting Error message as "Please enter a valid video URL. Valid URLs have a video file extension (.mp4, .webm, .ogv) or links to videos on YouTube or Vimeo."


Hence Confirming the issue.

Thanks.

**Comment by engcom-Bravo** [comment]
Hi @sprankhub,

Thank you for reporting and collaboration.

Verified the issue on Magento 2.4-develop instance and the issue is reproducible.Kindly refer the screenshots.

**Steps to reproduce**

- Create CMS page.
- Use page builder to add content.
- Add video element. Enter https://www.youtube-nocookie.com/embed/019DMLEVkos as "Video URL".
- Click "Save" button.

<img width="1496" alt="Screenshot 2023-11-24 at 2 16 40 PM" src="https://github.com/magento/magento2-page-builder/assets/51680745/67d4b448-3b28-4345-8271-e065d47e165d">



We are getting Error message as "Please enter a valid video URL. Valid URLs have a video file extension (.mp4, .webm, .ogv) or links to videos on YouTube or Vimeo."


Hence Confirming the issue.

Thanks.
